### ISSUE TITLE
CORS on node.js

### ISSUE THREAD

**Issue by hemanth** [monsur/enable-cors.org#45] opened 2013-09-04 03:54 UTC
Something like :  

``` javascript
if (req.method === 'OPTIONS') {
    var headers = {};
    headers["Access-Control-Allow-Origin"] = "*";
    headers["Access-Control-Allow-Methods"] = "POST, GET, PUT, DELETE, OPTIONS";
    headers["Access-Control-Allow-Credentials"] = true;
    headers["Access-Control-Max-Age"] = '86400'; // 24 hours
    headers["Access-Control-Allow-Headers"] = "X-Requested-With, Access-Control-Allow-Origin, X-HTTP-Method-Override, Content-Type, Authorization, Accept";
    res.writeHead(200, headers);
    res.end();
}
```

**Comment by monsur** [comment] 2013-11-19 22:06
Duplicate of https://github.com/monsur/enable-cors.org/pull/65

**Closed as completed by monsur** 2013-11-19 22:06 UTC
