### ISSUE TITLE
Please show how to enable CORS on Tomcat with Spring

### ISSUE THREAD

**Issue by neilmcguigan** [monsur/enable-cors.org#31] opened 2013-02-21 21:25 UTC
Thanks!

**Comment by monsur** [comment] 2013-02-22 03:52
Is there a particular method you have for enabling cors on Tomcat/Spring? I'm found the following: https://bitbucket.org/jsumners/corsfilter

**Comment by monsur** [comment] 2013-11-19 22:05
Duplicate of https://github.com/monsur/enable-cors.org/issues/43

**Closed as completed by monsur** 2013-11-19 22:05 UTC
