### ISSUE TITLE
this page:   http://enable-cors.org/server_nginx.html

### ISSUE THREAD

**Issue by synapsechris** [monsur/enable-cors.org#85] opened 2014-12-04 00:32 UTC
should have a link to the following:

http://wiki.nginx.org/IfIsEvil

I ran into some really weird behavior around if's within "location" statement just as the nginx site says.  And it might be good to warn people since your suggestion on the site is to use a bunch if IF statements.

I'm not saying your recipe doesn't work, only that when combined with other stuff, it may not work.

**Comment by monsur** [comment] 2014-12-08 22:09
Duplicate of #14. Sounds like I need to take a better look at how nginx is configured.

**Closed as completed** 2014-12-08 22:09 UTC
