### ISSUE TITLE
Add server configurations for nginx

### ISSUE THREAD

**Issue by algal** [monsur/enable-cors.org#36] opened 2013-05-08 10:40 UTC
I have developed an nginx configuration that implements CORS. It's on this gist: https://gist.github.com/algal/5480916 .

It handles preflight requests properly, allows for a whitelist of allowed origins, and has some comment on subtleties and browser issues for some of the other headers.

Would you like to add it to your list of server implementations?

**Comment by monsur** [comment] 2013-05-08 16:56
That looks great. Would you be open to submitting a pull request with this information? The HTML files live in the gh-pages branch. The server page is here: https://github.com/mhausenblas/enable-cors.org/blob/gh-pages/server.html  I think you'd have to add something new for nginx. Thanks!

**Comment by monsur** [comment] 2013-11-19 22:08
Duplicate of https://github.com/monsur/enable-cors.org/issues/14

**Closed as completed by monsur** 2013-11-19 22:08 UTC
